def runPipeline() {
    docker.image('alpine/curl:8.12.1').withRun('--net="k8s"') { c ->
        stage("Install kubectl") {
            sh "curl -LO https://dl.k8s.io/release/v1.32.0/bin/linux/amd64/kubectl"
            sh "chmod +x ./kubectl"
        }
        stage("Deploy application") {
            withChecks("Deploying application") {
                withCredentials([string(credentialsId: 'new_minikube_token', variable: 'api_token')]) {
                    sh './kubectl --token $api_token --server https://192.168.49.2:8443  --insecure-skip-tls-verify=true rollout restart -f ./deployment'
                    sh './kubectl --token $api_token --server https://192.168.49.2:8443 rollout status -f ./deployment --timeout=300s'
                }
            }
        }
    }
}

return this