def runPipeline(String branchName) {
    def DOCKER_REPO = "kacperkruger/board-games-app"

    stage("Install Dependencies") {
        docker.image('node:18-alpine').inside {
            sh "npm install"
        }
    }
    stage("Build") {
        withChecks("Build") {
            docker.image('node:18-alpine').inside {
                sh "npm run build"
            }
        }
    }
    stage("Test") {
        withChecks("Test") {
            docker.image('node:18-alpine').inside {
                sh "npm test"
            }
        }
    }
    stage("Build and Push Docker Image") {
        if (branchName == 'main' || branchName == 'develop' || branchName == 'staging') {
            steps {
                step("Build Docker Image") {
                    sh "docker build -t ${DOCKER_REPO}:${branchName} ."
                }
                step("Push Docker Image") {
                    withCredentials([usernamePassword(credentialsId: 'dockerHubCreds', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh 'echo \"$DOCKER_PASSWORD\" | docker login -u ${DOCKER_USERNAME} --password-stdin'
                    }
                    sh "docker push ${DOCKER_REPO}:${branchName}"
                }
                step("Remove Docker Image") {
                    sh "docker rmi ${DOCKER_REPO}:${branchName}"
                }
            }
        }
    }
}

return this