def runPipeline(String branchName) {
    def DOCKER_REPO = "kacperkruger/board-games-app"

    stage("Install Dependencies") {
        sh "cd BoardGamesApp && npm install"
    }
    stage("Build") {
        sh "cd BoardGamesApp && npm run build"
    }
    stage("Test") {
        sh "cd BoardGamesApp && npm test"
    }
    stage("Build Docker Image") {
        sh "cd BoardGamesApp && docker build -t ${DOCKER_REPO}:${branchName} ."
    }
    stage("Push Docker Image") {
        withCredentials([usernamePassword(credentialsId: 'dockerHubCreds', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
            sh 'echo \"$DOCKER_PASSWORD\" | docker login -u ${DOCKER_USERNAME} --password-stdin'
        }
        sh "docker push ${DOCKER_REPO}:${branchName}"
    }
    stage("Remove Docker Image") {
        sh "docker rmi ${DOCKER_REPO}:${branchName}"
    }
}

return this