def runPipeline(String branchName) {
    def DOCKER_REPO = "kacperkruger/board-games-app"

    stage("Install Dependencies") {
        sh "npm install"
    }
    stage("Build") {
        sh "npm run build"
    }
    stage("Test") {
        sh "npm test"
    }
    staeg("Build and Push Docker Image") {
        when {
            branch 'main'
        }
        stages {
            stage("Build Docker Image") {
                sh "docker build -t ${DOCKER_REPO}:${branchName} ."
            }
            stage("Push Docker Image") {
                withCredentials([usernamePassword(credentialsId: 'dockerHubCreds', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh 'echo \"$DOCKER_PASSWORD\" | docker login -u ${DOCKER_USERNAME} --password-stdin'
                }
                sh "docker push ${DOCKER_REPO}:${branchName}"
            }
            stage("Remove Docker Image") {
                sh "docker rmi ${DOCKER_REPO}:${branchName}"
            }
        }
    }
}

return this