def runPipeline(String branchName) {
    def DOCKER_REPO = "kacperkruger/board-games-reverse-proxy"

    stage("Build and Push Docker Image") {
        when {
            branch 'main'
        }
        steps {
            step("Build Docker Image") {
                sh "docker build -t ${DOCKER_REPO}:${branchName} ."
            }
            step("Push Docker Image") {
                withCredentials([usernamePassword(credentialsId: 'dockerHubCreds', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh 'echo \"$DOCKER_PASSWORD\" | docker login -u ${DOCKER_USERNAME} --password-stdin'
                }
                sh "docker push ${DOCKER_REPO}:${branchName}"
            }
            step("Remove Docker Image") {
                sh "docker rmi ${DOCKER_REPO}:${branchName}"
            }
        }
    }
}

return this