pipeline {
    agent any
    environment {
        DOCKER_REPO = "kacperkruger/board-games-reverse-proxy"
        IMAGE_TAG = "${env.BRANCH_NAME}"
    }
    stages {
        stage("Checkout") {
            steps {
                checkout scm
            }
        }
        stage("Build Docker Image") {
            steps {
                sh "cd BoardGamesApp && docker build -t ${DOCKER_REPO}:${IMAGE_TAG} ."
            }
        }
        stage("Push Docker Image") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerHubCreds', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh 'echo \"$DOCKER_PASSWORD\" | docker login -u ${DOCKER_USERNAME} --password-stdin'
                }
                sh "docker push ${DOCKER_REPO}:${IMAGE_TAG}"
            }
        }
    }
    post {
        always {
            sh "docker rmi ${DOCKER_REPO}:${IMAGE_TAG}"
            cleanWs()
        }
        success {
            echo "Build and push succeeded!"
        }
        failure {
            echo "Build and push failed!"
        }
    }
}
