apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: develop
spec:
  type: ClusterIP
  selector:
    app: mongodb
    type: database
  ports:
  - port:  27017
    targetPort: 27017
