apiVersion: v1
kind: Service
metadata:
  name: board-games-app-service
  namespace: staging
spec:
  type: ClusterIP
  selector:
    app: board-games-app
    type: frontend
  ports:
  - port: 8080
    targetPort: 8080
