apiVersion: v1
kind: Service
metadata:
  name: board-games-app-service
  namespace: main
spec:
  type: ClusterIP
  selector:
    app: board-games-app
    type: frontend
  ports:
  - port: 80
    targetPort: 80
