def runPipeline(String branchName) {
    def DOCKER_REPO = "kacperkruger/board-games-api"

    stage("Install Dependencies") {
        sh "npm install"
    }
    stage("Test") {
        withChecks("Test", includeStage: true) {
            sh "npm test"
        }
    }
    stage("Build and Push Docker Image") {
        when {
            branch 'main'
        }
        stages{
            stage("Build Docker Image") {
                sh "docker build -t ${DOCKER_REPO}:${branchName} ."
            }
            stage("Push Docker Image") {
                withCredentials([usernamePassword(credentialsId: 'dockerHubCreds', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh 'echo \"$DOCKER_PASSWORD\" | docker login -u ${DOCKER_USERNAME} --password-stdin'
                }
                sh "docker push ${DOCKER_REPO}:${branchName}"
            }
            stage("Remove Local Docker Image") {
                sh "docker rmi ${DOCKER_REPO}:${branchName}"
            }
        }
    }
}

return this